WebApplication1/Controllers/UsuarioController.cs
using DataAccessLayer;
using Shared.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Diagnostics;
using System.IO;
using Shared.DataTypes;

namespace WebApplication1.Controllers
{
    public class UsuarioController : Controller
    {

        IDALUsuario uC = new DALUsuarioEF();

        public class DatosUsuario
        {
            public string UsuarioID { get; set; }
            public string Nombre { get; set; }
            public string Apellido { get; set; }
            public string Pais { get; set; }
            public string Ciudad { get; set; }
            public string Direccion { get; set; }
            public string NumeroContacto { get; set; }
            public string Email { get; set; }
        }

        public class DataProductoUsuario
        {
            public long ProductoID { get; set; }
            public string nombre { get; set; }
        }

        public class DataCompraUsuario
        {
            public long ProductoID { get; set; }
            public int monto { get; set; }
        }

        public class DataCrearCalificacion
        {
            public long ProductoID { get; set; }
            public string UsuarioEvalua { get; set; }
            public string UsuarioCalificado { get; set; }

            public int puntaje { get; set; }
            public string comentario { get; set; }
        }

        // GET: Usuario
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                var url = Request.Url.LocalPath;
                return RedirectToAction("Login", "Account", new { ReturnUrl = Request.Url.LocalPath });
            }
            else
            {
                List<DataFactura> dfs = uC.ObtenerFactura(User.Identity.Name, Session["Tienda_Nombre"].ToString());
                dfs.Sort((x, y) => DateTime.Compare(x.fecha, y.fecha));
                int balance = 0;
                foreach (DataFactura df in dfs)
                {
                    if (df.esCompra)
                    {
                        balance -= df.monto;
                    }
                    else 
                    {
                        balance += df.monto;
                    }
                }
                ViewBag.Balance = balance;
                ViewBag.CompraVenta = dfs;
                return View();
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult obtenerJsonDatosUsuario(string userId)
        {
            try
            {
                Usuario u = uC.ObtenerUsuario(userId, Session["Tienda_Nombre"].ToString());
                var result = new { Success = "True", Usuario = u };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                var result = new { Success = "False", Message = e.Message };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            
        }

        // To convert the Byte Array to the author Image
        public FileContentResult getUserImg(String userId)
        {
            String tienda = Session["Tienda_Nombre"].ToString();
            ImagenUsuario iu = uC.ObtenerImagenUsuario(userId, tienda);
            if (iu != null)
            {
                byte[] byteArray = iu.Imagen; 
                return byteArray != null
                 ? new FileContentResult(byteArray, "image/jpeg")
                 : null;
            }
            else
            {
                var dir = Server.MapPath("~/Content/Images");
                var path = Path.Combine(dir, "user_sin_imagen.png");
                return new FileContentResult(System.IO.File.ReadAllBytes(path), "image/jpeg");
            }
        }

        [HttpPost]
        public JsonResult actualizarDatosUsuario(DatosUsuario du)
        {
            try
            {
                Usuario u = new Usuario
                {
                    UsuarioID = du.UsuarioID,
                    Nombre = du.Nombre,
                    Apellido = du.Apellido,
                    Pais = du.Pais,
                    Ciudad = du.Ciudad,
                    Direccion = du.Direccion,
                    NumeroContacto = du.NumeroContacto,
                    Email = du.Email
                };
                uC.ActualizarUsuario(u, Session["Tienda_Nombre"].ToString());
                var result = new { Success = "True", Message = "Usuario actualizado" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                var result = new { Success = "False", Message = e.Message };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public void UploadFile()
        {
            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                // Obtener la imagen subida
                var httpPostedFile = System.Web.HttpContext.Current.Request.Files["UploadedImage"];
                String usuarioId = User.Identity.Name;
                String tienda = Session["Tienda_Nombre"].ToString();
                if (httpPostedFile != null)
                {
                    byte[] imageBytes = null;
                    using (var binaryReader = new BinaryReader(httpPostedFile.InputStream))
                    {
                        imageBytes = binaryReader.ReadBytes(httpPostedFile.ContentLength);
                    }

                    ImagenUsuario iu = new ImagenUsuario{
                        UsuarioID = usuarioId,
                        Imagen    = imageBytes
                    };
                    //uC.EliminarImagenUsuario(usuarioId, tienda);
                    uC.AgregarImagenUsuario(iu, tienda);
                }
            }
        }

        public ActionResult CalificarUsuario(long prodId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                var url = Request.Url.LocalPath;
                return RedirectToAction("Login", "Account", new { ReturnUrl = Request.Url.LocalPath });
            }
            else
            {
                String tiendaId = Session["Tienda_Nombre"].ToString();
                String usuarioId = User.Identity.Name;
                DataPuedoCalificar dpc = uC.PuedoCalificar(prodId, usuarioId, tiendaId);
                ViewBag.DataCalificacion = dpc;
                return View();
            }
        }

        [Authorize]
        [HttpPost]
        public JsonResult agregarCalificacion(DataCrearCalificacion dcc)
        {
            String tiendaId = Session["Tienda_Nombre"].ToString();
            try
            {
                Calificacion c = new Calificacion
                {
                    ProductoID = dcc.ProductoID,
                    UsuarioEvalua = dcc.UsuarioEvalua,
                    UsuarioCalificado = dcc.UsuarioCalificado,
                    puntaje = dcc.puntaje,
                    comentario = dcc.comentario
                };
                uC.AgregarCalificacion(c, tiendaId);
                var result = new { Success = "True" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                var result = new { Success = "False", Message = e.Message };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Usuario/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Views/Usuario/CalificarUsuario.cshtml
@{
    ViewBag.Title = "CalificarUsuario";
    var dc = ViewBag.DataCalificacion;
}

<h2> Calificar compra </h2>
<div class="calificacion-container">


    @if (dc.puedoCalificar)
    {
        <div class="bs-callout bs-producto">
            <div class="datos-calif-left">
                <img src="@Url.Action("getProductImg", "Product", new { productId = @dc.idProd, index = 0 }) " class="img-centrada" width="150px" alt="Responsive image" />
            </div>
            <div class="datos-calificacion">
                <span class="labels-c"> <b> Producto: </b> @dc.nombreProd </span>
                <span class="labels-c"> <b> Vendedor: </b> @dc.idVendedor </span>  
                <span class="labels-c"> <b> Precio compra: </b> @dc.precioProd </span>
                <span class="labels-c"> <b> Fecha compra: </b> @dc.fecha_compra </span> 
            </div>
        </div>

        <div class="bs-callout bs-callout-info">
            <h4>1. ¿Ya recibiste el producto?</h4>
            <div class="radio">
                <label>
                    <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                    Sí, ya recibí el producto.
                </label>
            </div>
            <div class="radio">
                <label>
                    <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                    No recibí el producto.
                </label>
            </div>
        </div>

    <div class="bs-callout bs-callout-info">
        <h4>2. ¿Como calificas la compra? </h4>
        <input id="input-2c" class="rating" min="0" max="5" step="1" data-size="sm"
               data-symbol="&#xf005;" data-glyphicon="false" data-rating-class="rating-fa">
    </div>

    <div class="bs-callout bs-callout-info">
        <h4>3. ¿Algún comentario sobre la operación? </h4>
        <textarea class="form-control" id="calif-coment" rows="3"></textarea>
    </div>
        
    <div class="footer-calif">
        <button class="btn btn-default" id="confirmCalificacion"  style="float:right; margin-top: 20px" onclick="confirmarCalif()">Enviar calificación</button>
        <a class="button" id="btnFinalizarCalificacion" style="display:none; float: right" href="@Url.Action("Index", "Home")">Finalizar calificación</a>
    </div>
    }
    else
    {
       <h2>Usted no puede calificar esta compra.</h2> 
    }
</div>

<script>
    var ProductoID = "@dc.idProd"
    var UsuarioCalificado = "@dc.idVendedor"
    var UsuarioEvalua = "@Context.User.Identity.Name"
    $(document).ready(function () {
        $("#input-2c").rating();
    });

    confirmarCalif = function () {
        var rating = parseInt($("#input-2c").val(), 10),
            comentario = $("#calif-coment").val();
        if (!comentario) {
            comentario = "";
        }
        if (!rating) {
            swal("Datos incompletos", "Ingrese calificacion")
        } else {
            $("#confirmCalificacion").html("Enviar calificación" + "<i class=\"fa fa-spinner fa-pulse\"></i>");
            $.ajax({
                type: "POST",
                url: "@Url.Action("agregarCalificacion", "Usuario")",
                data: {
                    ProductoID: ProductoID,
                    UsuarioEvalua: UsuarioEvalua,
                    UsuarioCalificado: UsuarioCalificado,
                    puntaje: rating,
                    comentario: comentario
                },
                accept: 'application/json',
                success: function (response) {
                    swal("éxito!", "Tu calificación fue ingresada.", "success");
                    $("#confirmCalificacion").html("Enviar calificación");
                    $("#confirmCalificacion").hide();
                    $("#btnFinalizarCalificacion").show();
                },
                error: function (error) {
                    console.log(error);
                }
            });
        }

    }
</script>

<style>
    .bs-callout {
      padding: 20px;
      margin: 20px 0;
      border: 1px solid #eee;
      border-left-width: 5px;
      border-radius: 3px;
    }

    .bs-callout-info {
      border-left-color: #1b809e;
    }

    .bs-producto{
        border-color: #1b809e;
        height: 190px;
    }

    .datos-calif-left{
      width: 30%;
      float: left;
      border-right: 1px solid #eeeeee;
      height: 150px;
      display: inline-block;
    }

    .datos-calificacion{
        width: 60%;
        float: right;
        margin-left: 40px;
        display: block;
        margin-top: 20px;
    }

    .labels-c{
        display: inherit;

    }

    .rating-container{
        line-height: 50px !important;
    }
</style>

WebApplication1/Views/Usuario/Index.cshtml
@{
    ViewBag.Title = "Menu de usuario";
    var usuario = ViewBag.usuario;
}

<div class="titlefix">
    <h2>@ViewBag.Title.</h2>
</div>
<div style="width: 100%">
    <div role="tabpanel">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabUsuario">
            <li role="presentation" class="active"><a href="#perfil" aria-controls="perfil" role="tab" data-toggle="tab">Mi Perfil</a></li>
            <li role="presentation"><a href="#iniciarsubasta" aria-controls="iniciarsubasta" role="tab" data-toggle="tab">Iniciar subasta</a></li>
            <li role="presentation"><a href="#balance" aria-controls="balance" role="tab" data-toggle="tab">Balance montetario</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="perfil">
                @Html.Partial("_PerfilUsuarioPartial")
            </div>
            <div role="tabpanel" class="tab-pane fade" id="iniciarsubasta">
                @Html.Partial("_IniciarSubastaPartial")
            </div>
            <div role="tabpanel" class="tab-pane fade" id="balance">
                <div style="max-height: 600px; overflow-y: scroll;">
                    <table class="table">
                        <caption>Detalles</caption>
                        <thead>
                            <tr>
                                <th>
                                    Fecha
                                </th>
                                <th>
                                    Tipo
                                </th>
                                <th>
                                    Producto
                                </th>
                                <th>
                                    Monto
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var df in ViewBag.CompraVenta)
                            {
                                if (@df.esCompra)
                                {
                                    <tr>
                                        <td>
                                            @df.fecha
                                        </td>
                                        <td>
                                            Compra
                                        </td>
                                        <td>
                                            @df.nombreProducto <a href="@Url.Action("Details", "Product", new { productId = @df.ProductoID })"><i class="fa fa-external-link"></i></a>
                                        </td>
                                        <td>
                                            <span class="c-negative">
                                                @df.monto
                                            </span>
                                            <svg height="12px" width="12px">
                                                <path d="M2,2 L12,2 L7,10 Z" fill="#ff0000"></path>
                                            </svg>
                                        </td>
                                    </tr>
                                }
                                else
                                {
                                    <tr>
                                        <td>
                                            @df.fecha
                                        </td>
                                        <td>
                                            Venta
                                        </td>
                                        <td>
                                            @df.nombreProducto <a href="@Url.Action("Details", "Product", new { productId = @df.ProductoID })"><i class="fa fa-external-link"></i></a>
                                        </td>
                                        <td>
                                            <span class="c-negative">
                                                @df.monto
                                            </span>
                                            <svg height="12px" width="12px">
                                                <path d="M2,10 L7,1 L12,10 Z" fill="#A5DC86"></path>
                                            </svg>
                                        </td>
                                    </tr>
                                }
                            }
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <b>
                                        Balance: @ViewBag.Balance
                                    </b>
                                        @if (ViewBag.Balance > 0)
                                        {
                                            <svg height="12px" width="12px">
                                                <path d="M2,10 L7,1 L12,10 Z" fill="#A5DC86"></path>
                                            </svg>
                                        }
                                        else if (ViewBag.Balance < 0)
                                        {
                                            <svg height="12px" width="12px">
                                                <path d="M2,2 L12,2 L7,10 Z" fill="#ff0000"></path>
                                            </svg>
                                        }
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $(function () {
        $('#tabUsuario a[href="#perfil"]').tab('show')
    })
</script>

<style>
    .nav a {
        background: transparent;
    }
</style>

WebApplication1/Views/Usuario/_DatosAtributosPartial.cshtml
<section id="seccion-atributos">
    <h1>PASO 3: INGRESAR ATRIBUTOS DEL PRODUCTO</h1>

    <section id="content-atributos" data-request-url="@Url.Action("obtenerJsonAtributosCategoria", "Product")">
        Seleccione una categoría.
    </section>
    <div>
        <button class="btn btn-default" style="float:right" onclick="datosAtributos()">Siguiente</button>
        <button class="btn btn-default" style="float:left" onclick="volverProd('datosCategoria')">Anterior</button>
    </div>
</section>

<script id="atributos-template" type="text/x-template">
    {{#Atributos}}
    <div class="form-horizontal">
    {{>atributoItem}}
    </div>
    {{/Atributos}}
</script>

<script id="atributoItem" type="text/x-template">
    {{#esBool}}
    <div class="form-group">
        <label for="input-{{clave}}" class="col-sm-2 control-label">{{etiqueta}}</label>
        <select class="form-control" id="input-{{clave}}" style="margin-left: 15px; width: 10%; display: inline;">
            <option>Si</option>
            <option>No</option>
        </select>
    </div>
    {{/esBool}}
    {{^esBool}}
    <div class="form-group">
        <label for="input-{{clave}}" class="col-sm-2 control-label">{{etiqueta}}</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="input-{{clave}}">
        </div>
    </div>
    {{/esBool}}
</script>

WebApplication1/Views/Usuario/_DatosCategoriaPartial.cshtml
@{
    var nombreTienda = @Session["Tienda_Nombre"];
}

<div>
    <div id="divCategorias">
        <h1>PASO 2: SELECCIONAR CATEGORÍA</h1>
        <div id="categorias">
        </div>

        <div id="categoriaSeleccionada">
            
        </div>
        <div>
            <button class="btn btn-default" style="float:right" onclick="datosCat()">Siguiente</button>
            <button class="btn btn-default" style="float:left" onclick="volverProd('datosProducto')">Anterior</button>
        </div>
        
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#categorias').load("@Url.Action("MostrarCategorias", "Product")")
    })
</script>

WebApplication1/Views/Usuario/_DatosImagenesPartial.cshtml
<section id="seccion-imagenes">
    <h1>PASO 4: CARGAR IMÁGENES AL PRODUCTO</h1>

    <div>
        <label for="fileUpload"> Seleccione el archivo: </label>
        <input id="fileUploadProd" type="file" />
        <button id="btnImagenProd" class="btn btn-default" style="margin-top: 20px" type="submit"><i class="fa fa-camera-retro fa-2x"></i> Cargar imágen </button>
    </div>

    <div id="imagenesCargadas" style="margin:10px">

    </div>

    <a class="button" id="btnFinalizarSubasta" style="display:none; float: right" href="@Url.Action("Index", "Home")">Finalizar subasta</a>
</section>

<script type="text/javascript">
    $(document).ready(function () {
        var cantImagenes = 0;
        $('#btnImagenProd').on('click', function () {
            var files = $("#fileUploadProd").get(0).files;
            // Add the uploaded image content to the form data collection
            if (files.length > 0) {
                $("#btnImagenProd").html("Cargar imágen " + "<i class=\"fa fa-spinner fa-pulse\"></i>");
                var prodId = $("#seccion-imagenes").data('prodid');
                var data = new FormData();
                data.append("ProductoID", prodId);
                data.append("UploadedImage", files[0]);

                // Make Ajax request with the contentType = false, and procesDate = false
                var ajaxRequest = $.ajax({
                    type: "POST",
                    url: "@Url.Action("UploadFile", "Product")",
                    contentType: false,
                    processData: false,
                    data: data
                });

                ajaxRequest.done(function (xhr, textStatus) {
                    $("#btnImagenProd").html("<i class=\"fa fa-camera-retro fa-2x\"></i> Cargar imágen ");
                    var src = "@Url.Action("getProductImg", "Product")" + "?productId=" + prodId + "&index=" + cantImagenes;
                    var imgTemplate = "<img class=\"img-responsive\" style=\"display: inline\" src=\"" + src + "\" alt=\"Product Image\" width=\"150\" height=\"150\" />";
                    $("#imagenesCargadas").append(imgTemplate);
                    cantImagenes++;
                });
            } else {
                swal("Datos incompletos", "Debes seleccionar una imagen.");
            }
        });
    });
</script>

WebApplication1/Views/Usuario/_PerfilUsuarioPartial.cshtml
@{
    
}

<h3>Datos personales</h3>
<div class="perfil-user">
    <div class="perfil-user-datos">
        <div class="form-inline">
            <div class="form-group custom-form-group">
                <label for="exampleInputName2">Nombre</label>
                <input type="text" class="form-control" id="user-nombre" placeholder="Ingrese su nombre" value="">
            </div>
            <div class="form-group custom-form-group">
                <label for="exampleInputEmail2">Apellido</label>
                <input type="email" class="form-control" id="user-apellido" placeholder="Ingrese su apellido" value="">
            </div>
        </div>
        <div class="form-inline">
            <div class="form-group custom-form-group">
                <label for="exampleInputName2">Pais</label>
                <input type="text" class="form-control" id="user-pais" placeholder="Ingrese su país" value="">
            </div>
            <div class="form-group custom-form-group">
                <label for="exampleInputEmail2">Ciudad</label>
                <input type="text" class="form-control" id="user-ciudad" placeholder="Ingrese su ciudad">
            </div>
        </div>
        <div class="form-inline">
            <div class="form-group custom-form-group">
                <label for="exampleInputName2">Direccion</label>
                <input type="text" class="form-control" id="user-direccion" placeholder="Ingrese su dirección">
            </div>
            <div class="form-group custom-form-group">
                <label for="exampleInputEmail2">Número contacto</label>
                <input type="text" class="form-control" id="user-nrocontacto" placeholder="Ingrese su número de contacto">
            </div>
        </div>
        <div class="form-inline">
            <div class="form-group custom-form-group">
                <label for="exampleInputEmail2">Email</label>
                <input type="text" class="form-control" id="user-email" placeholder="Ingrese su email">
            </div>
        </div>
        
        <button type="button" id="btnActualizarDatos" class="btn btn-default" style="margin: 20px 5px 5px 5px;">Actualizar Datos</button>
    </div>
    <div class="perfil-user-img">
        <div>
            <img id="imgUser" class="img-responsive" src="@Url.Action("getUserImg", "Usuario", new { userId = @Context.User.Identity.Name })" alt="Person Image" />
        </div>
        <div class="form-group">
            <label for="exampleInputFile">Seleccionar archivo: </label>
            <input type="file" id="fileUploadUser">
            <p class="help-block">Imágen de perfil de usuario.</p>
        </div>

        <button type="button" id="btnUploadFileUser" class="btn btn-default">Cargar imágen</button>
    </div>
</div>
<script type="text/javascript">
    var userId = "@Context.User.Identity.Name"
    var isAuth = "@User.Identity.IsAuthenticated"

    $(document).ready(function () {

        $.ajax({
            type: "GET",
            url: "@Url.Action("obtenerJsonDatosUsuario", "Usuario")",
            data: {
                userId : userId
            },
            accept: 'application/json',
            success: function (data) {
                if (data.Usuario) {
                    var u = data.Usuario;
                    $("#user-nombre").val(u.Nombre);
                    $("#user-apellido").val(u.Apellido);
                    $("#user-ciudad").val(u.Ciudad);
                    $("#user-pais").val(u.Pais);
                    $("#user-direccion").val(u.Direccion);
                    $("#user-nrocontacto").val(u.NumeroContacto);
                    $("#user-email").val(u.Email);
                }
            },
            error: function (error) {
                sweetAlert("Oops...", error.Message, "error");
            }
        });
        $('#btnActualizarDatos').on('click', function () {

            var datosUsuario = {
                UsuarioID : userId,
                Nombre : $("#user-nombre").val(),
                Apellido: $("#user-apellido").val(),
                Ciudad: $("#user-ciudad").val(),
                Pais: $("#user-pais").val(),
                Direccion: $("#user-direccion").val(),
                NumeroContacto: $("#user-nrocontacto").val(),
                Email: $("#user-email").val()
            }
            $("#btnActualizarDatos").html($("#btnActualizarDatos").text() + " " + "<i class=\"fa fa-spinner fa-pulse\"></i>");
            $.ajax({
                type: "POST",
                url: "@Url.Action("actualizarDatosUsuario", "Usuario")",
                data: datosUsuario,
                accept: 'application/json',
                success: function (data) {
                    $("#btnActualizarDatos").html("Actualizar Datos");
                    swal("éxito!", "Tus datos fueron actualizados.", "success")
                },
                error: function (error) {
                    sweetAlert("Oops...", error.Message, "error");
                }
            });

        });

        $('#btnUploadFileUser').on('click', function () {
            var data = new FormData();
            var files = $("#fileUploadUser").get(0).files;
            // Add the uploaded image content to the form data collection
            if (files.length > 0) {
                $("#btnUploadFileUser").html("Cargar imágen " + "<i class=\"fa fa-spinner fa-pulse\"></i>");
                data.append("UploadedImage", files[0]);
                // Make Ajax request with the contentType = false, and procesDate = false
                var ajaxRequest = $.ajax({
                    type: "POST",
                    url: "@Url.Action("UploadFile", "Usuario")",
                    contentType: false,
                    processData: false,
                    data: data
                });

                ajaxRequest.done(function (xhr, textStatus) {
                    $("#btnUploadFileUser").html("Cargar imágen");
                    var src = $("#imgUser").attr('src');
                    $("#imgUser").attr('src', '');
                    setTimeout(function () {
                        $("#imgUser").attr('src', src);
                    }, 500);
                });
            } else {
                swal("Datos incompletos.", "Debes seleccionar una imagen.")
            }

           
        });
    });
</script>

<style>
    .custom-form-group{
        width: 45%;
        margin: 5px;
    }
</style>